### PR TITLE
Export Mural Card from Mural Picker [MI-758]

### PR DESCRIPTION
**Pull request by btuohy-mural**
https://github.com/MuralDevKit/mural-integrations-sdk/pull/86 except implemented differently.

### CODE REVIEW

**Review by KavenTheriault — APPROVED** [review]
LGTM

**Review by farminf — APPROVED** [review]
Looks Good Britt :shipit:

**Comment by btuohy-mural** [comment]
shipit

**Review by micaelbergeron — APPROVED** [review]
LGTM

**Pull request merged**
